-- Initial schema (PostgreSQL).
-- Column names/types mirror exactly what Hibernate (PostgreSQLDialect + Spring naming
-- strategy) generates for the JPA entities, so spring.jpa.hibernate.ddl-auto=validate
-- passes. Enum columns are VARCHAR with CHECK constraints listing the Java enum values.

CREATE TABLE users (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          VARCHAR(255) NOT NULL,
    email                         VARCHAR(255) NOT NULL,
    enabled                       BOOLEAN      NOT NULL,
    password                      VARCHAR(60),
    biography                     VARCHAR(255),
    location                      VARCHAR(255),
    phone_number                  VARCHAR(255),
    picture                       VARCHAR(255),
    alternative_email             VARCHAR(255),
    language_preference           VARCHAR(10),
    google_id                     VARCHAR(255),
    spotify_id                    VARCHAR(255),
    apple_id                      VARCHAR(255),
    soundcloud_id                 VARCHAR(255),
    primary_provider              VARCHAR(255) NOT NULL,
    theme_preference              VARCHAR(255),
    login_count                   INTEGER,
    profile_update_count          INTEGER,
    verification_token            VARCHAR(64),
    verification_token_expiry     TIMESTAMP(6) WITH TIME ZONE,
    password_reset_token          VARCHAR(64),
    password_reset_token_expiry   TIMESTAMP(6) WITH TIME ZONE,
    registration_date             TIMESTAMP(6) WITH TIME ZONE,
    last_updated                  TIMESTAMP(6) WITH TIME ZONE,
    last_login_date               TIMESTAMP(6) WITH TIME ZONE,
    last_active_date              TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_email      UNIQUE (email),
    CONSTRAINT uk_users_google     UNIQUE (google_id),
    CONSTRAINT uk_users_spotify    UNIQUE (spotify_id),
    CONSTRAINT uk_users_apple      UNIQUE (apple_id),
    CONSTRAINT uk_users_soundcloud UNIQUE (soundcloud_id),
    CONSTRAINT ck_users_primary_provider
        CHECK (primary_provider IN ('GOOGLE','LOCAL','SPOTIFY','APPLE','SOUNDCLOUD')),
    CONSTRAINT ck_users_theme_preference
        CHECK (theme_preference IN ('LIGHT','DARK','SYSTEM'))
);

CREATE TABLE user_roles (
    user_id BIGINT       NOT NULL,
    roles   VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_user_roles_roles
        CHECK (roles IN ('USER','ADMIN','MODERATOR','PREMIUM'))
);

CREATE TABLE user_notification_preferences (
    user_id               BIGINT NOT NULL,
    enabled_notifications VARCHAR(255),
    CONSTRAINT fk_notification_prefs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_notification_prefs_enabled
        CHECK (enabled_notifications IN (
            'EMAIL_GENERAL','EMAIL_MARKETING','EMAIL_SECURITY',
            'PUSH_GENERAL','PUSH_ACTIVITY','PUSH_MESSAGES',
            'IN_APP_GENERAL','IN_APP_ACTIVITY','IN_APP_MESSAGES'))
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_refresh_token      UNIQUE (token),
    CONSTRAINT uk_refresh_token_user UNIQUE (user_id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE profile_update_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_name  VARCHAR(255) NOT NULL,
    old_value   VARCHAR(1000),
    new_value   VARCHAR(1000),
    update_date TIMESTAMP(6) WITH TIME ZONE,
    user_id     BIGINT       NOT NULL,
    CONSTRAINT fk_profile_history_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(255) NOT NULL,
    principal   VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    details     VARCHAR(2000),
    outcome     VARCHAR(255),
    source      VARCHAR(255),
    ip_address  VARCHAR(255),
    user_agent  VARCHAR(255),
    timestamp   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT ck_audit_events_type CHECK (type IN (
        'LOGIN_SUCCESS','LOGIN_FAILURE','LOGOUT','TOKEN_REFRESH',
        'USER_CREATED','USER_UPDATED','USER_ROLE_CHANGED','USER_DELETED',
        'PROFILE_UPDATED','PROFILE_PICTURE_UPDATED','ACCESS_DENIED',
        'PERMISSION_CHANGE','CONFIG_CHANGED','SYSTEM_EVENT',
        'DATA_ACCESSED','DATA_CREATED','DATA_UPDATED','DATA_DELETED'))
);
