-- Tier 2a: MFA / TOTP. Per-user MFA state + a one-time recovery-code store.
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN totp_secret VARCHAR(255);

CREATE TABLE mfa_recovery_codes (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    used_at   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_mfa_recovery_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_mfa_recovery_code_hash UNIQUE (code_hash)
);
CREATE INDEX idx_mfa_recovery_user ON mfa_recovery_codes (user_id);
